name: PCDS Standard Testing

on:
  push:
    branches:
      - master
    paths-ignore:
  pull_request:
    branches:
      - master
  release:
    types:
      - created

jobs:
  standard:
    uses: pcdshub/pcds-ci-helpers/.github/workflows/twincat-standard.yml@master
    with:
      # The workflow can be configured to look at a specific project directory, if
      # desirable.  This defaults to the root of the repository (".").
      project-root: "."
      # Pattern (grep-compatible) of filenames to exclude in style checks.
      style-exclude: ""
